import { Route, Bus } from "./supabase";
// pre-defined routes used when the Supabase client isn't configured or
// the database has no data. Contains more than ten entries as requested.
// Image is served from public folder with base path
const BASE_PATH = '/Smart-Bus-Ticket-Booking-Platform/';
export const SAMPLE_ROUTES: Route[] = [
  {
    id: "sample-1",
    origin: "Mumbai",
    destination: "Pune",
    duration: "3h 15m",
    starting_price: 450,
    frequency: "Every 30 mins",
    image_url: BASE_PATH + "pune.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-2",
    origin: "Delhi",
    destination: "Agra",
    duration: "4h 0m",
    starting_price: 600,
    frequency: "Hourly",
    image_url: BASE_PATH + "agra.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-3",
    origin: "Chennai",
    destination: "Bangalore",
    duration: "6h 30m",
    starting_price: 800,
    frequency: "Daily",
    image_url: BASE_PATH + "bangalore.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-4",
    origin: "Kolkata",
    destination: "Darjeeling",
    duration: "12h 0m",
    starting_price: 1200,
    frequency: "Weekly",
    image_url: BASE_PATH + "darjeeling.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-5",
    origin: "Hyderabad",
    destination: "Vijayawada",
    duration: "4h 45m",
    starting_price: 550,
    frequency: "Every 2 hours",
    image_url: BASE_PATH + "vijayawada.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-6",
    origin: "Ahmedabad",
    destination: "Rajkot",
    duration: "3h 0m",
    starting_price: 400,
    frequency: "Daily",
    image_url: BASE_PATH + "rajkot.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-7",
    origin: "Jaipur",
    destination: "Udaipur",
    duration: "5h 30m",
    starting_price: 700,
    frequency: "Daily",
    image_url: BASE_PATH + "udaipur.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-8",
    origin: "Surat",
    destination: "Vadodara",
    duration: "2h 30m",
    starting_price: 350,
    frequency: "Every 90 mins",
    image_url: BASE_PATH + "vadodara.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-9",
    origin: "Lucknow",
    destination: "Varanasi",
    duration: "6h 0m",
    starting_price: 650,
    frequency: "Daily",
    image_url: BASE_PATH + "varanasi.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-10",
    origin: "Pune",
    destination: "Goa",
    duration: "10h 0m",
    starting_price: 1000,
    frequency: "Weekly",
    image_url: BASE_PATH + "goa.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-11",
    origin: "Chandigarh",
    destination: "Manali",
    duration: "8h 45m",
    starting_price: 900,
    frequency: "Daily",
    image_url: BASE_PATH + "manali.jpeg",
    created_at: new Date().toISOString(),
  },
  // Maharashtra routes
  {
    id: "sample-12",
    origin: "Mumbai",
    destination: "Nashik",
    duration: "3h 45m",
    starting_price: 500,
    frequency: "Every 30 mins",
    image_url: BASE_PATH + "nashik.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-13",
    origin: "Pune",
    destination: "Aurangabad",
    duration: "5h 30m",
    starting_price: 650,
    frequency: "Hourly",
    image_url: BASE_PATH + "aurangabad.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-14",
    origin: "Nagpur",
    destination: "Akola",
    duration: "2h 45m",
    starting_price: 400,
    frequency: "Every 2 hours",
    image_url: BASE_PATH + "akola.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-15",
    origin: "Kolhapur",
    destination: "Pune",
    duration: "4h 0m",
    starting_price: 550,
    frequency: "Daily",
    image_url: BASE_PATH + "pune.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-16",
    origin: "Akurdi",
    destination: "Mumbai",
    duration: "3h 30m",
    starting_price: 480,
    frequency: "Every 45 mins",
    image_url: BASE_PATH + "mumbai.jpeg",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-17",
    origin: "Satara",
    destination: "Aurangabad",
    duration: "6h 0m",
    starting_price: 700,
    frequency: "Daily",
    image_url: BASE_PATH + "aurangabad.jpeg",
    created_at: new Date().toISOString(),
  },
];

// sample bus entries corresponding to the sample routes. two buses per route.
export const SAMPLE_BUSES: Bus[] = [
  // Mumbai → Pune
  {
    id: "bus-mp-1",
    route_id: "sample-1",
    bus_name: "Mumbai Express",
    bus_type: "AC Seater",
    departure_time: "08:00",
    arrival_time: "11:15",
    price: 450,
    seats_available: 30,
    total_seats: 40,
    rating: 4.5,
    amenities: ["WiFi", "Charging Point"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-mp-2",
    route_id: "sample-1",
    bus_name: "Pune Superfast",
    bus_type: "Non AC Seater",
    departure_time: "10:00",
    arrival_time: "13:15",
    price: 400,
    seats_available: 20,
    total_seats: 40,
    rating: 4.0,
    amenities: ["Recliner"],
    created_at: new Date().toISOString(),
  },
  // Delhi → Agra
  {
    id: "bus-da-1",
    route_id: "sample-2",
    bus_name: "Agra Flyer",
    bus_type: "AC Sleeper",
    departure_time: "06:00",
    arrival_time: "10:00",
    price: 600,
    seats_available: 10,
    total_seats: 20,
    rating: 4.8,
    amenities: ["WiFi", "TV"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-da-2",
    route_id: "sample-2",
    bus_name: "Express Line",
    bus_type: "AC Seater",
    departure_time: "14:00",
    arrival_time: "18:00",
    price: 550,
    seats_available: 25,
    total_seats: 40,
    rating: 4.2,
    amenities: ["Charging Point"],
    created_at: new Date().toISOString(),
  },
  // additional buses for other routes
  {
    id: "bus-cb-1",
    route_id: "sample-3",
    bus_name: "Chennai Bangalore Superfast",
    bus_type: "Electric Luxury",
    departure_time: "09:00",
    arrival_time: "15:30",
    price: 800,
    seats_available: 15,
    total_seats: 20,
    rating: 4.9,
    amenities: ["WiFi", "Entertainment"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-cb-2",
    route_id: "sample-3",
    bus_name: "Bangalore Comfort",
    bus_type: "AC Seater",
    departure_time: "17:00",
    arrival_time: "23:30",
    price: 750,
    seats_available: 20,
    total_seats: 40,
    rating: 4.3,
    amenities: ["Charging Point"],
    created_at: new Date().toISOString(),
  },
  // additional buses for remaining routes
  {
    id: "bus-kd-1",
    route_id: "sample-4",
    bus_name: "Darjeeling Retreat",
    bus_type: "AC Sleeper",
    departure_time: "20:00",
    arrival_time: "08:00",
    price: 1200,
    seats_available: 5,
    total_seats: 20,
    rating: 4.7,
    amenities: ["Blanket", "WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-hv-1",
    route_id: "sample-5",
    bus_name: "Hyderabad Comfort",
    bus_type: "Non AC Seater",
    departure_time: "07:00",
    arrival_time: "11:45",
    price: 550,
    seats_available: 18,
    total_seats: 40,
    rating: 4.1,
    amenities: ["Charging Point"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-ar-1",
    route_id: "sample-6",
    bus_name: "Rajkot Express",
    bus_type: "AC Seater",
    departure_time: "12:00",
    arrival_time: "15:00",
    price: 400,
    seats_available: 22,
    total_seats: 40,
    rating: 4.0,
    amenities: ["WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-ju-1",
    route_id: "sample-7",
    bus_name: "Udaipur Cruiser",
    bus_type: "AC Sleeper",
    departure_time: "06:30",
    arrival_time: "12:00",
    price: 700,
    seats_available: 10,
    total_seats: 20,
    rating: 4.4,
    amenities: ["WiFi", "Charging Point"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-sv-1",
    route_id: "sample-8",
    bus_name: "Vadodara Connector",
    bus_type: "Non AC Seater",
    departure_time: "09:00",
    arrival_time: "11:30",
    price: 350,
    seats_available: 30,
    total_seats: 40,
    rating: 3.9,
    amenities: [],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-lv-1",
    route_id: "sample-9",
    bus_name: "Varanasi Express",
    bus_type: "AC Seater",
    departure_time: "08:00",
    arrival_time: "14:00",
    price: 650,
    seats_available: 20,
    total_seats: 40,
    rating: 4.2,
    amenities: ["WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-pg-1",
    route_id: "sample-10",
    bus_name: "Goa Holiday",
    bus_type: "AC Sleeper",
    departure_time: "22:00",
    arrival_time: "08:00",
    price: 1000,
    seats_available: 8,
    total_seats: 20,
    rating: 4.6,
    amenities: ["Recliner", "WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-cm-1",
    route_id: "sample-11",
    bus_name: "Manali Voyager",
    bus_type: "AC Sleeper",
    departure_time: "18:00",
    arrival_time: "02:45",
    price: 900,
    seats_available: 12,
    total_seats: 20,
    rating: 4.8,
    amenities: ["Blanket", "WiFi"],
    created_at: new Date().toISOString(),
  },
  // Maharashtra routes buses
  {
    id: "bus-mn-1",
    route_id: "sample-12",
    bus_name: "Nashik Express",
    bus_type: "AC Seater",
    departure_time: "08:00",
    arrival_time: "11:30",
    price: 500,
    seats_available: 28,
    total_seats: 40,
    rating: 4.3,
    amenities: ["WiFi", "Charging Point"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-mn-2",
    route_id: "sample-12",
    bus_name: "Mumbai Nashik Superfast",
    bus_type: "Non AC Seater",
    departure_time: "14:00",
    arrival_time: "17:45",
    price: 450,
    seats_available: 32,
    total_seats: 40,
    rating: 4.0,
    amenities: ["Recliner"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-pa-1",
    route_id: "sample-13",
    bus_name: "Aurangabad Luxury",
    bus_type: "AC Sleeper",
    departure_time: "19:00",
    arrival_time: "00:30",
    price: 650,
    seats_available: 15,
    total_seats: 20,
    rating: 4.6,
    amenities: ["Blanket", "WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-pa-2",
    route_id: "sample-13",
    bus_name: "Pune Aurangabad Comfort",
    bus_type: "AC Seater",
    departure_time: "07:00",
    arrival_time: "12:30",
    price: 600,
    seats_available: 25,
    total_seats: 40,
    rating: 4.2,
    amenities: ["Charging Point"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-na-1",
    route_id: "sample-14",
    bus_name: "Akola Direct",
    bus_type: "Non AC Seater",
    departure_time: "07:00",
    arrival_time: "09:45",
    price: 400,
    seats_available: 35,
    total_seats: 40,
    rating: 3.8,
    amenities: [],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-na-2",
    route_id: "sample-14",
    bus_name: "Nagpur Akola Express",
    bus_type: "AC Seater",
    departure_time: "15:00",
    arrival_time: "17:45",
    price: 420,
    seats_available: 30,
    total_seats: 40,
    rating: 4.1,
    amenities: ["WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-kp-1",
    route_id: "sample-15",
    bus_name: "Kolhapur Comfort",
    bus_type: "AC Sleeper",
    departure_time: "21:00",
    arrival_time: "01:00",
    price: 550,
    seats_available: 16,
    total_seats: 20,
    rating: 4.4,
    amenities: ["Blanket", "WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-kp-2",
    route_id: "sample-15",
    bus_name: "Kolhapur Pune Daily",
    bus_type: "AC Seater",
    departure_time: "08:00",
    arrival_time: "12:00",
    price: 520,
    seats_available: 26,
    total_seats: 40,
    rating: 4.0,
    amenities: ["Charging Point"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-am-1",
    route_id: "sample-16",
    bus_name: "Akurdi Mumbai Superfast",
    bus_type: "AC Seater",
    departure_time: "08:00",
    arrival_time: "11:30",
    price: 480,
    seats_available: 32,
    total_seats: 40,
    rating: 4.2,
    amenities: ["WiFi", "Charging Point"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-am-2",
    route_id: "sample-16",
    bus_name: "Mumbai Express (Evening)",
    bus_type: "Non AC Seater",
    departure_time: "16:00",
    arrival_time: "19:30",
    price: 450,
    seats_available: 28,
    total_seats: 40,
    rating: 3.9,
    amenities: ["Recliner"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-sa-1",
    route_id: "sample-17",
    bus_name: "Satara Aurangabad Luxury",
    bus_type: "AC Sleeper",
    departure_time: "20:00",
    arrival_time: "02:00",
    price: 700,
    seats_available: 12,
    total_seats: 20,
    rating: 4.7,
    amenities: ["Blanket", "WiFi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "bus-sa-2",
    route_id: "sample-17",
    bus_name: "Satara Aurangabad Comfort",
    bus_type: "AC Seater",
    departure_time: "08:00",
    arrival_time: "14:00",
    price: 680,
    seats_available: 24,
    total_seats: 40,
    rating: 4.3,
    amenities: ["Charging Point"],
    created_at: new Date().toISOString(),
  },
];
